server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前的数据库操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://47.93.23.231:3306/dbCloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: juhick
    password: qhq21131411

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
       #defaultZone: http://localhost:7001/eureka #单机版
       defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka/ #集群版

  instance:
    instance-id: payment8001
    prefer-ip-address: true
#    #Eureka客户端向服务端发送心跳的时间间隔， 单位为秒
#    lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒，超时剔除服务
#    lease-expiration-duration-in-seconds: 2

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.qhq.springcloud.entities #所有entities别名类所在包
